# This is a basic workflow to help you get started with Actions

name: KeepAlive

# Controls when the action will run. 
on:
  schedule:
    - cron: '*/7 * * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Poll our application with a network request.
      # Replace --url with your deployed app's URL.
      - name: Poll Application
        run: |
          curl --request GET \ 
          --url 'https://gapp-discord-bot.wl.r.appspot.com'
          
