# KeepAlive action.
name: KeepAlive

# Controls when the action will run. 
on:
  schedule:
    - cron: "*/7 * * * *"
    
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      # Poll our application with a network request.
      # Replace --url with your deployed app's URL.
      - name: Send request to endpoint.
        run: |
          curl --request GET --url "https://gapp-discord-bot.wl.r.appspot.com"
          
